[project]
name = "simbora"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-encrypted-model-fields==0.6.5",
    "django==5.1.14",
    "dynaconf>=3.2.12",
    "pillow==12.0.0",
    "python-dotenv==1.2.1",
]
